#!/bin/sh

### BEGIN INIT INFO
# Provides:			 ThisSocks_C
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ThisSocks client init script
# Description:       This script used to start/stop ThisSocks client
### END INIT INFO

EXEC=ThisSocks
NAME=ThisSocks_C
CONF=client.conf
DESC="ThisSocks client"

. /etc/init.d/ThisSocks
