#!/bin/sh

### BEGIN INIT INFO
# Provides:			 ThisSocks_S
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ThisSocks server init script
# Description:       This script used to start/stop ThisSocks server
### END INIT INFO

EXEC=ThisSocks
NAME=ThisSocks_S
CONF=server.conf
DESC="ThisSocks server"

. /etc/init.d/ThisSocks
